export class Perfiles {
	
	public static ADMINISTRACION = 1;
	public static USUARIO_PETICIONARIO = 2;
	public static ADMINISTRACION_ROLES = 3;
	public static ADMINISTRACION_FUNCIONES = 4;
	public static CONSULTAS_EMPLEADOS = 5;
	public static CONSULTAS_EMPLEADOS_EMPLEADOS = 6;
	public static CONSULTAS_EMPLEADOS_EMPLEADOS_DATOS_GENERALES = 7;
	public static CONSULTAS_EMPLEADOS_EMPLEADOS_DATOS_EMPRESARIALES = 8;
	public static CONSULTAS_EMPLEADOS_EMPLEADOS_COMPENSACION = 9;
	public static CONSULTAS_EMPLEADOS_EMPLEADOS_DATOS_BANCARIOS = 10;
	public static CONSULTAS_EMPLEADOS_EMPLEADOS_RESUMEN_FECHAS = 11;
	public static CONSULTAS_EMPLEADOS_EMPLEADOS_PRESTACIONES = 12;
	public static CONSULTAS_EMPLEADOS_EMPLEADOS_DATOS_COMPLEMENTARIOS = 13;
	public static CONSULTAS_EMPLEADOS_MOVIMIENTOS = 14;
	public static CONSULTAS_EMPLEADOS_MOVIMIENTOS_RECIBOS_NOMINA = 15;
	public static CONSULTAS_EMPLEADOS_MOVIMIENTOS_VACACIONES_PERMISOS = 16;
	public static CONSULTAS_EMPLEADOS_MOVIMIENTOS_MOVIMIENTOS = 17;
	public static CONSULTAS_EMPLEADOS_MOVIMIENTOS_HISTORICOS = 18;
	public static CONSULTAS_EMPLEADOS_MOVIMIENTOS_COMPLEMENTARIOS = 19;
	public static CONSULTAS_EMPLEADOS_REPORTES = 20;
	public static CONSULTAS_EMPLEADOS_REPORTES_GENERALES = 21;
	public static CONSULTAS_EMPLEADOS_REPORTES_RESERVADOS = 22;
	public static ESTRUCTURA_DE_EMPLEADOS = 23;
	public static CONSULTA_DE_CANDIDATOS = 24;

	
	
}
